CREATE TABLE issues (
  id SERIAL PRIMARY KEY,
  issue_date DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  brand VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  issue TEXT NOT NULL CHECK (ISSUE != ''),
  resolution TEXT NOT NULL CHECK (RESOLUTION != ''),
  issue_embedding vector(768)
);

INSERT INTO issues (id, issue_date, brand, model, issue, resolution) 
VALUES 
(1, '2022-01-01', 'Samsung', 'Galaxy S21', 'The screen of my phone suddenly broke.', 'Replaced the screen'),
(2, '2021-12-15', 'Apple', 'iPhone 13', 'My battery is completely drained after using the phone for 8 hours.', 'Replaced the battery'),
(3, '2022-02-10', 'Google', 'Pixel 5', 'The camera on my phone is not focusing properly.', 'Cleaned the lens and recalibrated the camera'),
(4, '2021-11-20', 'OnePlus', '9 Pro', 'My phone is overheating when I use it for extended periods.', 'Cleaned dust from the vents and applied thermal paste'),
(5, '2022-03-01', 'Huawei', 'Mate 30', 'I am not getting any signal even though I have full coverage.', 'Reset the network settings and checked for physical damage'),
(6, '2021-12-01', 'Xiaomi', 'Mi 10', 'The fingerprint scanner on my phone is not working properly.', 'Cleaned the sensor and recalibrated it'),
(7, '2022-01-15', 'LG', 'G8X ThinQ', 'The audio on my phone is distorted when watching videos.', 'Replaced the speakers and updated the firmware'),
(8, '2021-11-25', 'Sony', 'Xperia 1 II', 'The screen is too bright even when turned down.', 'Cleaned the display and adjusted the backlight'),
(9, '2022-02-15', 'Oppo', 'Find X3 Pro', 'The charging port on my phone is damaged.', 'Replaced the charging port and updated the firmware'),
(10, '2021-12-15', 'Asus', 'Zenfone 7', 'My battery lasts only a few hours.', 'Cleaned dust from the vents and applied thermal paste'),
(11, '2022-01-01', 'Honor', '20 Pro', 'The front camera on my phone is not working properly.', 'Replaced the front camera'),
(12, '2021-11-15', 'Motorola', 'G Stylus', 'I am experiencing a screen freeze issue with my phone.', 'Rebooted the phone and updated the firmware'),
(13, '2022-02-01', 'Nokia', '8.3', 'The audio jack on my phone is not working properly.', 'Cleaned the port and applied thermal paste'),
(14, '2021-12-15', 'TCL', 'Xiaomi 10S', 'My phone is experiencing a random shutdown issue.', 'Replaced the battery and checked for physical damage'),
(15, '2022-01-15', 'Lenovo', 'ThinkPad X1 Carbon', 'The keyboard on my laptop is not typing properly.', 'Cleaned the keys and recalibrated the keyboard'),
(16, '2021-12-01', 'Samsung', 'Galaxy S21', 'My phone is overheating when I use it for extended periods.', 'Cleaned dust from the vents and applied thermal paste'),
(17, '2022-02-10', 'Apple', 'iPhone 13', 'The screen on my phone is not responding properly.', 'Rebooted the phone and updated the firmware'),
(18, '2021-11-20', 'OnePlus', '9 Pro', 'Audio is distorted when playing videos.', 'Cleaned the speakers and recalibrated the audio'),
(19, '2022-03-01', 'Huawei', 'Mate 30', 'I am not getting any signal even though I have full coverage.', 'Reset the network settings and checked for physical damage'),
(20, '2021-12-15', 'Xiaomi', 'Mi 10', 'Fingerprint scanner is not working properly.', 'Cleaned the sensor and recalibrated it'),
(21, '2022-01-15', 'LG', 'G8X ThinQ', 'The camera on my phone is not focusing properly.', 'Cleaned the lens and recalibrated the camera'),
(22, '2021-11-25', 'Sony', 'Xperia 1 II', 'Screen is too bright even when turned down.', 'Cleaned the display and adjusted the backlight'),
(23, '2022-02-15', 'Oppo', 'Find X3 Pro', 'The charging port on my phone is damaged.', 'Replaced the charging port and updated the firmware'),
(24, '2021-12-15', 'Asus', 'Zenfone 7', 'My battery lasts only a few hours.', 'Cleaned dust from the vents and applied thermal paste'),
(25, '2022-01-01', 'Honor', '20 Pro', 'The front camera on my phone is not working properly.', 'Replaced the front camera'),
(26, '2021-11-15', 'Motorola', 'G Stylus', 'I am experiencing a screen freeze issue with my phone.', 'Rebooted the phone and updated the firmware'),
(27, '2022-02-01', 'Nokia', '8.3', 'The audio jack on my phone is not working properly.', 'Cleaned the port and applied thermal paste'),
(28, '2021-12-15', 'TCL', 'Xiaomi 10S', 'My phone is experiencing a random shutdown issue.', 'Replaced the battery and checked for physical damage'),
(29, '2022-01-15', 'Lenovo', 'ThinkPad X1 Carbon', 'The keyboard on my laptop is not typing properly.', 'Cleaned the keys and recalibrated the keyboard'),
(30, '2021-12-01', 'Samsung', 'Galaxy S21', 'Screen is responsive but slow.', 'Rebooted the phone and updated the firmware'),
(31, '2022-02-10', 'Apple', 'iPhone 13', 'The fingerprint scanner on my phone is not working properly.', 'Cleaned the sensor and recalibrated it'),
(32, '2021-11-20', 'OnePlus', '9 Pro', 'Audio is distorted when playing videos.', 'Cleaned the speakers and recalibrated the audio'),
(33, '2022-03-01', 'Huawei', 'Mate 30', 'I am not getting any signal even though I have full coverage.', 'Reset the network settings and checked for physical damage'),
(34, '2021-12-15', 'Xiaomi', 'Mi 10', 'Front camera is not working properly.', 'Replaced the front camera'),
(35, '2022-01-15', 'LG', 'G8X ThinQ', 'The keyboard on my laptop is not typing properly.', 'Cleaned the keys and recalibrated the keyboard'),
(36, '2021-11-25', 'Sony', 'Xperia 1 II', 'Screen is responsive but slow.', 'Rebooted the phone and updated the firmware'),
(37, '2022-02-15', 'Oppo', 'Find X3 Pro', 'The charging port on my phone is damaged.', 'Replaced the charging port and updated the firmware'),
(38, '2021-12-15', 'Asus', 'Zenfone 7', 'My battery lasts only a few hours.', 'Cleaned dust from the vents and applied thermal paste'),
(39, '2022-01-01', 'Honor', '20 Pro', 'The audio jack on my phone is not working properly.', 'Cleaned the port and applied thermal paste'),
(40, '2021-11-15', 'Motorola', 'G Stylus', 'I am experiencing a screen freeze issue with my phone.', 'Rebooted the phone and updated the firmware'),
(41, '2022-02-01', 'Nokia', '8.3', 'Fingerprint scanner is not working properly.', 'Cleaned the sensor and recalibrated it'),
(42, '2021-12-15', 'TCL', 'Xiaomi 10S', 'My phone is experiencing a random shutdown issue.', 'Replaced the battery and checked for physical damage'),
(43, '2022-01-15', 'Lenovo', 'ThinkPad X1 Carbon', 'The keyboard on my laptop is not typing properly.', 'Cleaned the keys and recalibrated the keyboard'),
(44, '2021-12-01', 'Samsung', 'Galaxy S21', 'Screen is responsive but slow.', 'Rebooted the phone and updated the firmware'),
(45, '2022-02-10', 'Apple', 'iPhone 13', 'The audio on my phone is distorted when playing videos.', 'Cleaned the speakers and recalibrated the audio'),
(46, '2021-11-20', 'OnePlus', '9 Pro', 'Front camera is not working properly.', 'Replaced the front camera'),
(47, '2022-03-01', 'Huawei', 'Mate 30', 'I am not getting any signal even though I have full coverage.', 'Reset the network settings and checked for physical damage'),
(48, '2021-12-15', 'Xiaomi', 'Mi 10', 'Screen is too bright even when turned down.', 'Cleaned the display and adjusted the backlight'),
(49, '2022-01-15', 'LG', 'G8X ThinQ', 'The keyboard on my laptop is not typing properly.', 'Cleaned the keys and recalibrated the keyboard'),
(50, '2021-11-25', 'Sony', 'Xperia 1 II', 'Fingerprint scanner is not working properly.', 'Cleaned the sensor and recalibrated it');